/*
 * BTE API
 * Discord Bot API
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Player;
import org.junit.Ignore;
import org.junit.Test;

/**
 * API tests for ModApi
 */
@Ignore
public class ModApiTest {

    private final ModApi api = new ModApi();

    /**
     * Get player data
     * <p>
     * Queries data for a joining player.  This is used by the mod to get information about the permissions and names the player has - if any.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPlayerTest() throws ApiException {
        String uuid = null;
        Player response = api.getPlayer(uuid);

        // TODO: test validations
    }
}
